service: serverless-cf-cache-purger
useDotenv: true

frameworkVersion: "2"

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  purgeCloudFlare:
    handler: handler.purgeCloudFlare
    events:
      - httpApi:
          method: POST
          path: '/purge'
